# FM5252 Blackscholes implimentation
#--------------------------------------
# Most of the formulas were taken from
#+[the course website]
#+(https://proutymfm.azurewebsites.net)
#
# The formulas that weren't provided were
#+either found in John C. Hull - 11e (2022)
#+"Options, Future, and Other Derivatives"
#+or were just changed to use the apppropriate
#option (put or call) and underlying.
#
# Some of the formulas are redundant, but
#+who cares.
#
# TODO: add better logic for plotting
# TODO: look for other todo notes below
# TODO: refine blackscholes method
#+namely, extract the plotting logic
# TODO: make this in C????C++???
#
#Author: Dominic Cook <cook0707@umn.edu>
#Date: March 20, 2026
#License: MIT

# ----- Imports -----
# for differentiating lambda functions
from sympy import *
# both needed for lambdify for some
#+unknown reason
import numpy as np
import scipy
# plotting library
import matplotlib.pyplot as plt
# for CLI
import argparse

# --- Instantiate Symbols ---
# sympyify the symbols
# S: Spot price
# K: Strike price
# r: rate (risk-free?)
# vol: volatility of the underlying
# T: time horizon in years
S, K, r, vol, T = symbols('S, K, r, vol, T', real = True)

# --- List of Sympy-ified Methods ---
def d1():
    # this is the d1 from the black-scholes-merton model
    # i don't really know what it is....
    #+some kind of moneyness or something???
    # it's used as a <generator?> of a normal cdf
    # See Hull (2022) Ch 15 pg 353
    d = (log(S / K)+((r + (vol ** 2) / 2) * T)) / (vol * sqrt(T))
    return d

def d2():
    # this is the d2 from the black-scholes-merton model
    # i don't really know what it is....
    #+some kind of moneyness or something???
    # it's used as a <generator?> of a normal cdf
    # NOTE: d2 could also be defined as:
    #+(log(S / K)+(r+(vol ** 2) / 2) * T) / (vol * sqrt(T)) - vol * sqrt(T)
    d = (log(S / K)+(r - (vol ** 2) / 2) * T) / (vol * sqrt(T))
    return d

def callprice():
    # this calculates black-scholes call price
    # define the call price formula
    px = S * (0.5 * (1 + erf(d1() / sqrt(2)))) - K * exp(-r*T) * (0.5 * (1+erf(d2() / sqrt(2))))
    return px

def putprice():
    # this calculates black-scholes put price
    # define the put price formula
    px = K * exp(-r*T) *  (0.5 * (1 + erf(-d2() / sqrt(2)))) - S * (0.5 * (1 + erf(-d1() / sqrt(2))))
    return px

def delta(is_call: bool=True):
    return diff(callprice(), S) if is_call else diff(putprice(), S)

def gamma(is_call: bool=True):
    # NOTE: this is just diff(diff(price(), S))
    # NOTE: call and put prices yield the same gamma
    #+but the option to print using either is for any
    #+possible arbitrage opportunity
    return diff(delta(), S) if is_call else diff(delta(is_call=False), S)

def theta(is_call: bool):
    # NOTE: THIS IS AN ARTIFICIAL THETA!!!!
    #+AND IT WAS ONLY ADDED BECAUSE THE TA TOOK OFF POINTS FOR
    #+SUBMITTING A POSITIVE THETA!!!!
    # TODO: FIX THE THETA CALC SO IT'S NEGATIVE BY DESIGN??????
    return -diff(callprice(), T) if is_call else -diff(putprice(), T)

def vega(is_call: bool=True):
    # NOTE: call and put prices yield the same gamma
    #+but the option to print using either is for any
    #+possible arbitrage opportunity
    return diff(callprice(), vol) if is_call else diff(putprice(), vol)

def rho(is_call: bool):
    return diff(callprice(), r) if is_call else diff(putprice(), r)

def black_scholes (
        spot: float=28,
        strike: float=30,
        rate: float=0.05,
        volatility: float=0.5,
        horizon: int=1,
        mode='print',
        run_mode: str="jdi",
        x_var='S',
        y_var=None,
        steps=100,
        # this next option will return a
        #+tuple of call and put price
        #just give me the gosh darn price
        jgmtgdp=None,
):
    '''
            Black Scholes Functionification
            -------------------------------

            mode:
                can be either print, plot, or compare.
                print will print to stout,
                plot will plot all the greeks.
                compare will plot greeks with respect to underlying param.

            x_var:
                by default will be underlying stock price

            y_var:
                not necessary but if passed, will plot the given greek name
                found in the dictionary. (only use with mode='compare')

            steps:
                default is 100 steps. it dictates how many points are
                generated by the default spectruminator.
    '''

    # define real values needed for evaluation
    #+but store them in a dictionary so you
    #+can programmatically pick ones to vectorize.
    # if run_mode interactive, then take user option params
    if run_mode == "interactive":
        defaults = {
            "S": float(input("spot quote: ")),
            "K": float(input("strike: ")),
            "r": float(input("risk-free rate: ")),
            "vol": float(input("volatility: ")),
            "T": int(input("horizon (in years): ")),
        }
    # else just use whatever default params are set
    else:
        defaults = {
            "S": spot,
            "K": strike,
            "r": rate,
            "vol": volatility,
            "T": horizon,
        }

    # define a default spectrum of reasonable
    #+ranges for each parameter.
    # TODO: edit these params to be variable
    #+based on the given input. (how? idk)
    def_spectrum = {
        "S": np.linspace(10, 150, steps),
        "K": np.linspace(10, 150, steps),
        "r": np.random.normal(0.05, 0.01, steps),
        "vol": np.random.normal(0.5, 0.9, steps),
        "T": np.linspace(1, 50, steps),
    }

    # calculate call and put price
    callpx = callprice()
    putpx = putprice()

    # the below expressions were stolen from other people
    # See instructors website: Week3 Lecture
    # See Hull (2022)
    expressions = {
            "call price": callprice(),
            "put price": putprice(),
            "call delta": delta(is_call=True),
            "put delta": delta(is_call=False),
            # as mentioned before, theoretically
            #+call and put gamma and theta should
            #+should be equal
            "call gamma": gamma(),
            "put gamma": gamma(is_call=False),
            "call vega": vega(),
            "put vega": vega(is_call=False),
            "call theta": -diff(callpx, T),
            "put theta": -diff(putpx, T),
            "call rho": diff(callpx, r),
            "put rho": diff(putpx, r),
    }

    # lambdify all of the expressions, being sure to load
    #+both numpy and scipy upon lambdification.
    # the expressions will need numpy for vector
    #+operations, and scipy for graphing.
    # if you try to run this without loading scipy in the modules
    #+the interpreter will begin to softly weep.
    # all lambdified expressions are stored in a dict called <fns>
    fns = {
        name: lambdify((S, K, r, vol, T), expr,
                       modules=['numpy', 'scipy']) for name, expr in expressions.items()
    }

    # print a nice chart to stdout
    #+with all the greeks calculated
    #+with the default parameters.
    if mode == 'print':
        print("-" * 30)
        print(f"{'Greek':<12} | {'Value':<10}")
        print("-" * 30)
        for name, fn in fns.items():
            val = fn(**defaults)
            print(f"{name:<12} | {float(val):.8f}")

    # plot all the greeks with default
    #+parameters over a change in spot (S).
    elif mode == 'plot':
        # vectorize the price by assigning
        #+one of the values in the default
        #+dictionary of parameters one of the
        #+spectrums defined in the default spectrum.
        defaults[x_var] = def_spectrum[x_var]
        # define the domain for the plot
        x_range = defaults[x_var]

        # evalute all greek functions
        for name, fn in fns.items():
            y_values = fn(**defaults)

            # force the vector shapes to match
            if np.isscalar(y_values):
                y_values = np.full_like(x_range, y_values)

            plt.plot(x_range, y_values, label=name)

        plt.title(f"Option Greeks vs {x_var}")
        plt.xlabel(f"Underlying {x_var}")
        plt.ylabel("Value")
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.show()

    # optionally plot 1 variable
    #+against one of the greeks
    elif mode == 'compare':
        # vecorize the given parameter
        #+with the default_spectruminator
        defaults[x_var] = def_spectrum[x_var]
        x_range = def_spectrum[x_var]

        # evaluate the across the given greek
        for name, fn in fns.items():
            y_values = fns[y_var](**defaults)
            y_values = np.full_like(x_range, y_values)
            plt.plot(x_range, y_values, label=name)

        plot_title = f"{x_var} and {y_var}"
        plt.title(plot_title)
        plt.xlabel(f"{x_var}")
        plt.ylabel(f"{y_var}")
        plt.grid(True, alpha=0.3)
        plt.show()

def main():
    # initialize parser with option parameters
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", type=str, default="print", choices=["print", "plot", "compare"])
    parser.add_argument("-S", "--spot", type=float)
    parser.add_argument("-K", "--strike", type=float)
    parser.add_argument("-r", "--rate", type=float)
    parser.add_argument("-v", "--volatility", type=float)
    parser.add_argument("-T", "--horizon", type=int)
    parser.add_argument("-i", "--interactive", action="store_true")
    args = parser.parse_args()

    user_rm="DEFAULT"
    if args.interactive:
        user_rm="interactive"

    black_scholes(mode=args.mode, run_mode=user_rm)

if __name__ == "__main__":
    main()
